### ISSUE TITLE
[REQ] \e\ build

### ISSUE THREAD

**Issue by MarcoRavich** [GS290-dev/android_device_gigaset_mt6763-common#2]
Hi there,
it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) for GS290 too.

Someone opened a 3ad @ [\e\ community](https://community.e.foundation/) were we also linked your repos:

https://community.e.foundation/t/gigaset-gs5-with-e-os/40181

Hope can "inspire" you.

Thanks in advance.

**Comment by erfanoabdi** [comment]
https://github.com/GS290-dev/local_manifests/blob/main/NOTICE
